---
title: "Population in Germany by federal states"
subtitle: "Developing Data Products - Assignment 2"
author: "Jakob Schelbert"
date: "23 March 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r importpackages, echo=FALSE, warning=FALSE}
suppressPackageStartupMessages({
library(shiny)
library(leaflet)
library(dplyr)
library(jsonlite)
library(geojsonio)
library(rgdal)
})
```

This file implements some nice features of the `leaflet` package. More information can be found on the appropriate [website](https://rstudio.github.io/leaflet/choropleths.html).

We use a `geojson` file taken from [Github](https://github.com/isellsoap/deutschlandGeoJSON) and population data from [Statista](https://de.statista.com/statistik/daten/studie/71085/umfrage/verteilung-der-einwohnerzahl-nach-bundeslaendern/) (numbers from 2015).
In addition, I added two markers that indicate my academic background (just for fun).
```{r generate_data, echo=FALSE}
#data taken from https://de.statista.com/statistik/daten/studie/71085/umfrage/verteilung-der-einwohnerzahl-nach-bundeslaendern/
population <- round(c(17865.52,12843.51,10879.62,7926.6,6176.17,4084.85,4052.8,3520.03,2858.71,2484.83,2245.47,2170.71,1787.41,1612.36,995.6,671.49)/1000, 1)
pop_struct <- structure(list(ID_1 = c(10, 2, 1, 9, 7, 14, 11, 3, 15, 4, 13, 16, 6, 8,12, 5), 
                        population = population), 
          row.names = c(NA, -8L), 
          class = c("data.table", "data.frame"), 
          .Names = c("ID_1", "population"))

#geojson taken from https://github.com/isellsoap/deutschlandGeoJSON
geojson <- readLines("4_niedrig.geojson", warn = FALSE) %>%
  paste(collapse = "\n") %>%
  fromJSON(simplifyVector = FALSE)
geo_data <- geojson_read("4_niedrig.geojson", what="sp")
geo_data <- merge(geo_data, pop_struct)

uni_geodata <- data.frame(
    lat = c(49.57390, 49.87861),
    lng = c(11.03005, 8.65726)
)
uni_Sites <- c(
    "<a href='https://mso.math.fau.de/edom/'>FAU Erlangen-Nuremberg - Chair of EDOM</a>",
    "<a href='http://www3.mathematik.tu-darmstadt.de/'>TU Darmstadt - Mathematics</a>"
)
```

## Leaflet map
```{r generate_map1, echo=FALSE}
labels <- sprintf(
    "<strong>%s</strong><br/> %gM inhabitants",
    geo_data$NAME_1, geo_data$population
) %>% lapply(htmltools::HTML)

pal <- colorNumeric("Greens", domain=geo_data$population)

m <- leaflet(geo_data) %>% 
    addProviderTiles(providers$CartoDB.Positron) %>% 
    addPolygons(fillColor = ~pal(population),
                weight = 2,
                opacity = 1,
                color = "white",
                dashArray = "3",
                fillOpacity = 0.7,
                highlight = highlightOptions(
                    weight = 5,
                    color = "#666",
                    dashArray = "",
                    fillOpacity = 0.7,
                    bringToFront = TRUE),
                label = labels,
                labelOptions = labelOptions(
                    style = list("font-weight" = "normal", padding = "3px 8px"),
                    textsize = "15px",
                    direction = "auto")) %>% 
    addLegend(pal = pal, 
              values = ~population, 
              opacity = 0.7, 
              title = "Population in Mio.", 
              position = "bottomright") %>% 
    addMarkers(data=uni_geodata, popup = uni_Sites)
m
```


## Code
```{r, ref.label=knitr::all_labels(), echo=TRUE, eval=FALSE, tidy=TRUE}
```